/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.23
 * Generated at: 2015-07-29 00:31:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.page;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class project_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/page/footer.jsp", Long.valueOf(1438129431949L));
    _jspx_dependants.put("/WEB-INF/lib/javax.servlet.jsp.jstl-1.2.1.jar", Long.valueOf(1436152923064L));
    _jspx_dependants.put("/WEB-INF/page/header.jsp", Long.valueOf(1438129431949L));
    _jspx_dependants.put("jar:file:/D:/Git/Liboutcomes-Homepage/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/LibOutcomesWeb/WEB-INF/lib/javax.servlet.jsp.jstl-1.2.1.jar!/META-INF/c.tld", Long.valueOf(1323225978000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	String loginId = (String) session.getAttribute("liboutcomes_login");

	pageContext.setAttribute("loginId", loginId);

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"x-ua-compatible\" content=\"IE=9\"/>\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    \r\n");
      out.write("    <!-- 웹 페이지 제목 -->\r\n");
      out.write("    <title>LIBOUTCOMES</title>\r\n");
      out.write("\r\n");
      out.write("    <!-- 부트스트랩 -->\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/css/bootstrap.min.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/font-awesome/css/font-awesome.min.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("    <!-- 슬라이더 -->\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/css/owl.carousel.css\" rel=\"stylesheet\" media=\"screen\">\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/css/owl.theme.css\" rel=\"stylesheet\" media=\"screen\">\r\n");
      out.write("\r\n");
      out.write("    <!-- 스타일 -->\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/css/style.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/css/responsive.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("    \r\n");
      out.write("    <!-- Summernote -->\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/css/summernote.css\" rel=\"stylesheet\">\r\n");
      out.write(" \r\n");
      out.write("</head>\r\n");
      out.write("\t\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <!-- Navigation -->\r\n");
      out.write("\t<nav id=\"tf-menu\" class=\"navbar navbar-default navbar-fixed-top\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<!-- Brand and toggle get grouped for better mobile display -->\r\n");
      out.write("\t\t\t<div class=\"navbar-header\">\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"navbar-toggle collapsed\" data-toggle=\"collapse\" data-target=\"#bs-example-navbar-collapse-1\">\r\n");
      out.write("\t\t            <span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("\t\t            <span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t            <span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t            <span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t<a class=\"navbar-brand\" href=\"/LibOutcomesWeb\">LibOutcomes</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t        <!-- Collect the nav links, forms, and other content for toggling -->\r\n");
      out.write("\t        <div class=\"collapse navbar-collapse navbar-right\" id=\"bs-example-navbar-collapse-1\">\r\n");
      out.write("\t\t\t\t<ul class=\"nav navbar-nav\">\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"Project\">프로젝트 소개</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"Library\">도서관 DB</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("\t\t\t\t\t<li class=\"dropdown\">\r\n");
      out.write("                        <a href=\"#\" class=\"page-scroll\" data-toggle=\"dropdown\">데이터 사이언스 <b class=\"caret\"></b></a>\r\n");
      out.write("                        <ul class=\"dropdown-menu\">\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"DataScienceManual\">메뉴얼</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"DataScienceReference\">적용사례</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"Board\">게시판</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"nav navbar-right\" style=\"padding-right:15px;\">\r\n");
      out.write("\t\t\t\t\t<!-- 세션 체크로 변경 -->\r\n");
      out.write("                    ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                    ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- /.navbar-collapse -->\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- /.container-fluid -->\r\n");
      out.write("\t</nav>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 프로젝트 소개 \r\n");
      out.write("==========================================-->\r\n");
      out.write("\r\n");
      out.write("<div id=\"tf-services\" class=\"text-center\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("    \t\r\n");
      out.write("    \t<!-- 제목 -->\r\n");
      out.write("    \t<div class=\"space\"></div>\r\n");
      out.write("        <div class=\"section-title center\">\r\n");
      out.write("            <h2><strong>LibOutcomes</strong> 프로젝트</h2>\r\n");
      out.write("            <div class=\"line\">\r\n");
      out.write("                <hr>\r\n");
      out.write("            </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"space\"></div>\r\n");
      out.write("\t\t<!-- /.제목 -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- 내용 -->\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-lg-12 text-center\">\r\n");
      out.write("          \t\t<h3>공공도서관 서비스 가치평가 모델 개발 및 소프트웨어 구축 과제</h3>\r\n");
      out.write("          \t\t<h3 class=\"text-muted\"><small>Modeling the Values of Public Library Services and Software Development</small></h3>\r\n");
      out.write("                <div class=\"space\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("      \t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-8 col-md-offset-2\">\r\n");
      out.write("\t\t\t\t\t<p>2012년 ACRL(미국 대학 및 연구도서관 협회)은 도서관의 10대 핵심 이슈 중 하나로 ‘도서관 가치 알리기(Communicating value)’를 선정한 바 있다. \r\n");
      out.write("\t\t\t\t\t\t이는 도서관의 가치를 알리고 이를 통해 지역사회에서 변화와 소통에 주도적인 역할을 주문하는 것이다. 도서관이 지역사회와 소통하기 위해서는 무엇보다 올바른 평가를 통한 가치의 발견이 선행되어야 함은 물론이다.</p>\r\n");
      out.write("      \t \t\t\t<p>그간 도서관에서 수행한 평가는 이용자의 만족도 조사 혹은 서비스 산출 평가(Output evaulation) 위주로 되어 있어 지역사회 내에서 도서관이 만들어내는 변화와 성과를 충분히 보여주지 못하여 도서관이 가진 가치에 비해 \r\n");
      out.write("      \t \t\t\t\t상대적으로 낮은 인식을 받아왔다. 또한 내부적으로도 도서관에 축적된 데이터를 평가에 다양하게 활용할 수 있음에도 불구하고 단순 기술통계로 사용하고 있어 도서관 데이터 활용의 효율성을 제고할 필요가 있는 상황이다.</p>\r\n");
      out.write("      \t \t\t\t<p>따라서 본 연구는 공공도서관의 가치를 계량적으로 제시할 수 있는 성과 평가(Outcome evaluation) 모델을 개발하기 위해 도서관에서 기존에 축적한 데이터를 활용하여 도서관의 가치 평가 지표를 설계하고 지표를 \r\n");
      out.write("      \t \t\t\t\t측정하는 것을 목적으로 한다. 본 목적을 달성하기 위해서 구체적으로는 공공도서관의 다양한 서비스를 다차원으로 분석하고, 공공도서관의 데이터를 활용한 지표를 개발한 후 로직모델(Logic model)을 바탕으로 \r\n");
      out.write("      \t \t\t\t\t평가 프레임워크를 개발한다. 이를 바탕으로 ‘LibOutcomes software’를 개발하여 도서관의 성과와 가치를 보여줄 수 있는 평가도구로 활용하고자 한다.</p>\r\n");
      out.write("      \t\t\t\t<p>본 연구를 통해 다음과 같은 효과를 얻을 수 있을 것으로 기대한다.</p>\r\n");
      out.write("      \t\t\t</div>\r\n");
      out.write("      \t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- /.내용 -->\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 프로젝트 기대 효과\r\n");
      out.write("==========================================-->\r\n");
      out.write("<div id=\"tf-services\" class=\"text-center\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("    \r\n");
      out.write("    \t<!-- 제목 -->\r\n");
      out.write("        <div class=\"section-title center\">\r\n");
      out.write("            <h2>프로젝트 <strong>기대 효과</strong></h2>\r\n");
      out.write("            <div class=\"line\">\r\n");
      out.write("                <hr>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"clearfix\"></div>\r\n");
      out.write("            <small><em>Expectation Effectiveness for the Project</em></small>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"space\"></div>\r\n");
      out.write("        <!-- /.제목 -->\r\n");
      out.write("        \r\n");
      out.write("        <!-- 내용 -->\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-md-4 service\">\r\n");
      out.write("                <i class=\"fa fa-bar-chart\"></i>\r\n");
      out.write("                <h4><strong>올바른 평가 & 가치 알리기</strong></h4>\r\n");
      out.write("                <p>지역사회에 대한 공공도서관의 성과에 대한 평가를 수행함으로써 공공도서관의 프로그램 운영에 대한 올바른 평가와 가치 알리기가 가능해질 것이다. \r\n");
      out.write("                \t아울러, 도서관을 이용하는 지역사회 주민과의 지속적인 연계 및 관계 유지에 유용하게 이용될 것이다.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"col-md-4 service\">\r\n");
      out.write("                <i class=\"fa fa-book\"></i>\r\n");
      out.write("                <h4><strong>업무 개선 & 사업 확장</strong></h4>\r\n");
      out.write("                <p>공공도서관 업무 개선 및 사업의 확장이 가능할 것이다. 이제 단순 수치만으로 도서관을 평가할 수는 없다. 지속적인 가치의 평가와 이용자 서비스의 개발을 통해 지역사회와의 소통에 구심점으로 자리매김해야 할 것이다.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"col-md-4 service\">\r\n");
      out.write("                <i class=\"fa fa-plane\"></i>\r\n");
      out.write("                <h4><strong>문헌정보학계의 발전</strong></h4>\r\n");
      out.write("                <p>평가모델의 공유를 통한 문헌정보학계의 발전을 도모할 수 있을 것이다. 과거의 여러 연구를 통해 평가의 영역이 현재도 여러 문제점이 있으나 개선 및 새로운 지표의 개발이 용이하지 않다는 것을 목도해 왔다. \r\n");
      out.write("                \t따라서 본 연구를 통해 성과의 평가라는 새로운 화두를 던질 수 있을 것이다.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- /.내용 -->\r\n");
      out.write("        \r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 프로젝트 진행 방향\r\n");
      out.write("==========================================-->\r\n");
      out.write("<div id=\"tf-services\" class=\"text-center\">\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- 제목 -->\r\n");
      out.write("    \t<div class=\"section-title center\">\r\n");
      out.write("            <h2>프로젝트 <strong>진행 방향</strong></h2>\r\n");
      out.write("            <div class=\"line\">\r\n");
      out.write("                <hr>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"clearfix\"></div>\r\n");
      out.write("            <small><em>Direction of Progress for the Project</em></small>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"space\"></div>\r\n");
      out.write("        <!-- /.제목 -->\r\n");
      out.write("        \r\n");
      out.write("        <!-- 내용 -->\r\n");
      out.write("\t    <div class=\"row\">\r\n");
      out.write("\t        <div class=\"col-lg-12\">\r\n");
      out.write("\t            <ul class=\"timeline\">\r\n");
      out.write("\t            \r\n");
      out.write("\t                <li class=\"timeline-inverted\">\r\n");
      out.write("\t                    <div class=\"timeline-image\">\r\n");
      out.write("\t                        <img class=\"img-circle img-responsive\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/img/project2.jpg\">\r\n");
      out.write("\t                    </div>\r\n");
      out.write("\t                    <div class=\"timeline-panel\">\r\n");
      out.write("\t                        <div class=\"timeline-heading\">\r\n");
      out.write("\t                            <h4>2015-2016</h4>\r\n");
      out.write("\t                            <h4 class=\"subheading\">1년차 활동내용</h4>\r\n");
      out.write("\t                        </div>\r\n");
      out.write("\t                        <div class=\"timeline-body\">\r\n");
      out.write("\t                            <p class=\"text-muted\">① 도서관 서비스 성과평가 모형개발 (성북정보도서관 서비스 분석 / 성과평가 워크숍 / 성과지표 개발 / 성과평가 모델 프레임워크 개발)</p> \r\n");
      out.write("\t                            <p class=\"text-muted\">② LibOutcomes 개발 (평가업무 프로세스분석 / KOLAS 시스템 저장 데이터 DB 구조 분석 / 유사 DB 설계 및 기획 / LibOutcomes Prototype 설계 및 구현 / 간단한 UI를 이용한 구현 및 테스트)</p>\r\n");
      out.write("\t                            <p class=\"text-muted\">③ 성과확산을 위한 웹사이트 구축 (콘텐츠 구축 / 웹사이트 구축 / 웹사이트 시범운영 / 웹사이트 공개)</p>\r\n");
      out.write("\t                        </div>\r\n");
      out.write("\t                    </div>\r\n");
      out.write("\t                </li>\r\n");
      out.write("\t                \r\n");
      out.write("\t                <li class=\"timeline-inverted\">\r\n");
      out.write("\t                    <div class=\"timeline-image\">\r\n");
      out.write("\t                        <img class=\"img-circle img-responsive\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/img/project3.jpg\">\r\n");
      out.write("\t                    </div>\r\n");
      out.write("\t                    <div class=\"timeline-panel\">\r\n");
      out.write("\t                        <div class=\"timeline-heading\">\r\n");
      out.write("\t                            <h4>2016-2017</h4>\r\n");
      out.write("\t                            <h4 class=\"subheading\">2년차 활동내용</h4>\r\n");
      out.write("\t                        </div>\r\n");
      out.write("\t                        <div class=\"timeline-body\">\r\n");
      out.write("\t                            <p class=\"text-muted\">① 도서관 시스템 환경분석 (KOLAS 시스템 저장 데이터 분석 / KOLAS 시스템 DB 구조 분석 / 기존 DB외 추가 입력될 데이터 분석)</p>\r\n");
      out.write("\t                            <p class=\"text-muted\">② LibOutcomes 개발 (LibOutcomes DB 설계 / LibOutcomes DB 구현 / 웹사이트와 LibOutcomes 연동 / 시범 운영, 테스트 및 시스템 공개)</p>\r\n");
      out.write("\t                            <p class=\"text-muted\">③ LibOutcomes 확산을 위한 전략 (시스템 활용 매뉴얼 개발 / LibOutcomes 워크숍)</p>\r\n");
      out.write("\t                        </div>\r\n");
      out.write("\t                    </div>\r\n");
      out.write("\t                </li>\r\n");
      out.write("\t                \r\n");
      out.write("\t                <li class=\"timeline-inverted\">\r\n");
      out.write("\t                    <div class=\"timeline-image\">\r\n");
      out.write("\t                        <h4>Be Part\r\n");
      out.write("\t                            <br>Of Our\r\n");
      out.write("\t                            <br>Story!</h4>\r\n");
      out.write("\t                    </div>\r\n");
      out.write("\t                </li>\r\n");
      out.write("\t                \r\n");
      out.write("\t            </ul>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t    <!-- /.내용 -->\r\n");
      out.write("\t    \r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 프로젝트 연구원 구성\r\n");
      out.write("==========================================-->\r\n");
      out.write("<div id=\"tf-team\" class=\"text-center\">\r\n");
      out.write("    <div class=\"overlay\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("        \r\n");
      out.write("        \t<!-- 제목 -->\r\n");
      out.write("            <div class=\"section-title center\">\r\n");
      out.write("                <h2>프로젝트 <strong>연구원 구성</strong></h2>\r\n");
      out.write("                <div class=\"line\">\r\n");
      out.write("                    <hr>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- /.제목 -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- 내용 -->\r\n");
      out.write("            <div id=\"team\" class=\"owl-carousel owl-theme row\">\r\n");
      out.write("            \r\n");
      out.write("                <div class=\"item\">\r\n");
      out.write("                    <div class=\"thumbnail\">\r\n");
      out.write("                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/img/member/박성재.png\" class=\"img-circle team-img\">\r\n");
      out.write("                        <div class=\"caption\">\r\n");
      out.write("                            <h3>박성재</h3>\r\n");
      out.write("                            <p>한성대 지식정보학부 교수</p>\r\n");
      out.write("                            <p>Do not seek to change what has come before. Seek to create that which has not.</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"item\">\r\n");
      out.write("                    <div class=\"thumbnail\">\r\n");
      out.write("                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/img/member/조세홍.png\" class=\"img-circle team-img\">\r\n");
      out.write("                        <div class=\"caption\">\r\n");
      out.write("                            <h3>조세홍</h3>\r\n");
      out.write("                            <p>한성대 멀티미디어공학과 교수</p>\r\n");
      out.write("                            <p>Do not seek to change what has come before. Seek to create that which has not.</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"item\">\r\n");
      out.write("                    <div class=\"thumbnail\">\r\n");
      out.write("                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/img/member/한상우.png\" class=\"img-circle team-img\">\r\n");
      out.write("                        <div class=\"caption\">\r\n");
      out.write("                            <h3>한상우</h3>\r\n");
      out.write("                            <p>BeAdded</p>\r\n");
      out.write("                            <p>Do not seek to change what has come before. Seek to create that which has not.</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"item\">\r\n");
      out.write("                    <div class=\"thumbnail\">\r\n");
      out.write("                        <img src=\"http://placehold.it/200x200\" class=\"img-circle team-img\">\r\n");
      out.write("                        <div class=\"caption\">\r\n");
      out.write("                            <h3>김정환</h3>\r\n");
      out.write("                            <p>한성대 지식정보학부</p>\r\n");
      out.write("                            <p>Do not seek to change what has come before. Seek to create that which has not.</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"item\">\r\n");
      out.write("                    <div class=\"thumbnail\">\r\n");
      out.write("                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/img/member/이제진.png\" class=\"img-circle team-img\">\r\n");
      out.write("                        <div class=\"caption\">\r\n");
      out.write("                            <h3>이제진</h3>\r\n");
      out.write("                            <p>한성대 지식정보학부</p>\r\n");
      out.write("                            <p>가치평가 모델 개발에 참여하고 있습니다. 나태하지만 꼼꼼한 이십대입니다.</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"item\">\r\n");
      out.write("                    <div class=\"thumbnail\">\r\n");
      out.write("                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/img/member/박준민.png\" class=\"img-circle team-img\">\r\n");
      out.write("                        <div class=\"caption\">\r\n");
      out.write("                            <h3>박준민</h3>\r\n");
      out.write("                            <p>개발 팀장</p>\r\n");
      out.write("                            <p>웹 프론트엔드와 백엔드에 관심이 많은 웹개발자입니다</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"item\">\r\n");
      out.write("                    <div class=\"thumbnail\">\r\n");
      out.write("                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/img/member/박미현.png\" class=\"img-circle team-img\">\r\n");
      out.write("                        <div class=\"caption\">\r\n");
      out.write("                            <h3>박미현</h3>\r\n");
      out.write("                            <p>한성대 멀티미디어공학과</p>\r\n");
      out.write("                            <p>Do not seek to change what has come before. Seek to create that which has not.</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"item\">\r\n");
      out.write("                    <div class=\"thumbnail\">\r\n");
      out.write("                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/img/member/윤민정.jpg\" class=\"img-circle team-img\">\r\n");
      out.write("                        <div class=\"caption\">\r\n");
      out.write("                            <h3>윤민정</h3>\r\n");
      out.write("                            <p>한성대 멀티미디어공학과</p>\r\n");
      out.write("                            <p>빅데이터를 기반으로 한 웹 전문가를 꿈꾸고 있습니다.</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"item\">\r\n");
      out.write("                    <div class=\"thumbnail\">\r\n");
      out.write("                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/img/member/이지아.png\" class=\"img-circle team-img\">\r\n");
      out.write("                        <div class=\"caption\">\r\n");
      out.write("                            <h3>이지아</h3>\r\n");
      out.write("                            <p>한성대 멀티미디어공학과</p>\r\n");
      out.write("                            <p>Do not seek to change what has come before. Seek to create that which has not.</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            \t\r\n");
      out.write("                <div class=\"item\">\r\n");
      out.write("                    <div class=\"thumbnail\">\r\n");
      out.write("                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/img/member/정유진.png\" class=\"img-circle team-img\">\r\n");
      out.write("                        <div class=\"caption\">\r\n");
      out.write("                            <h3>정유진</h3>\r\n");
      out.write("                            <p>한성대 멀티미디어공학과</p>\r\n");
      out.write("                            <p>모바일과 서버사이드 쪽 개발에 관심이 많습니다. 한 분야에만 치우치지 않는 풀스텍 개발자가 목표입니다.</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("        \t</div>\r\n");
      out.write("        \t<!-- /.내용 -->\r\n");
      out.write("        \t\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 프로젝트 관련 사진\r\n");
      out.write("==========================================-->\r\n");
      out.write("<div id=\"tf-works\">\r\n");
      out.write("    <div class=\"container\"> <!-- Container -->\r\n");
      out.write("        <div class=\"section-title text-center center\">\r\n");
      out.write("            <h2>프로젝트 <strong>관련 사진</strong></h2>\r\n");
      out.write("            <div class=\"line\">\r\n");
      out.write("                <hr>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"clearfix\"></div>\r\n");
      out.write("            <small><em>Photo or Image of the project</em></small>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"space\"></div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"categories\">\r\n");
      out.write("            \r\n");
      out.write("            <ul class=\"cat\">\r\n");
      out.write("                <li class=\"pull-left\"><h4>Filter by Type:</h4></li>\r\n");
      out.write("                <li class=\"pull-right\">\r\n");
      out.write("                    <ol class=\"type\">\r\n");
      out.write("                        <li><a href=\"#\" data-filter=\"*\" class=\"active\">All</a></li>\r\n");
      out.write("                        <li><a href=\"#\" data-filter=\".model\">성과 모델링</a></li>\r\n");
      out.write("                        <li><a href=\"#\" data-filter=\".sysetm\">시스템 개발</a></li>\r\n");
      out.write("                        <li><a href=\"#\" data-filter=\".etc\" >기타 이미지</a></li>\r\n");
      out.write("                    </ol>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <div class=\"clearfix\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div id=\"lightbox\" class=\"row\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"col-sm-6 col-md-3 col-lg-3 model\">\r\n");
      out.write("                <div class=\"portfolio-item\">\r\n");
      out.write("                    <div class=\"hover-bg\">\r\n");
      out.write("                        <a href=\"#\">\r\n");
      out.write("                            <div class=\"hover-text\">\r\n");
      out.write("                                <h4>Sample Image</h4>\r\n");
      out.write("                                <small>Will be changed</small>\r\n");
      out.write("                                <div class=\"clearfix\"></div>\r\n");
      out.write("                                <i class=\"fa fa-plus\"></i>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/img/portfolio/01.jpg\" class=\"img-responsive\" alt=\"...\">\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"col-sm-6 col-md-3 col-lg-3 model sysetm\">\r\n");
      out.write("                <div class=\"portfolio-item\">\r\n");
      out.write("                    <div class=\"hover-bg\">\r\n");
      out.write("                        <a href=\"#\">\r\n");
      out.write("                            <div class=\"hover-text\">\r\n");
      out.write("                                <h4>Sample Image</h4>\r\n");
      out.write("                                <small>Will be changed</small>\r\n");
      out.write("                                <div class=\"clearfix\"></div>\r\n");
      out.write("                                <i class=\"fa fa-plus\"></i>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/img/portfolio/02.jpg\" class=\"img-responsive\" alt=\"...\">\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"col-sm-6 col-md-3 col-lg-3 sysetm\">\r\n");
      out.write("                <div class=\"portfolio-item\">\r\n");
      out.write("                    <div class=\"hover-bg\">\r\n");
      out.write("                        <a href=\"#\">\r\n");
      out.write("                            <div class=\"hover-text\">\r\n");
      out.write("                                <h4>Sample Image</h4>\r\n");
      out.write("                                <small>Will be changed</small>\r\n");
      out.write("                                <div class=\"clearfix\"></div>\r\n");
      out.write("                                <i class=\"fa fa-plus\"></i>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/img/portfolio/03.jpg\" class=\"img-responsive\" alt=\"...\">\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"col-sm-6 col-md-3 col-lg-3 etc\">\r\n");
      out.write("                <div class=\"portfolio-item\">\r\n");
      out.write("                    <div class=\"hover-bg\">\r\n");
      out.write("                        <a href=\"#\">\r\n");
      out.write("                            <div class=\"hover-text\">\r\n");
      out.write("                                <h4>Sample Image</h4>\r\n");
      out.write("                                <small>Will be changed</small>\r\n");
      out.write("                                <div class=\"clearfix\"></div>\r\n");
      out.write("                                <i class=\"fa fa-plus\"></i>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/img/portfolio/04.jpg\" class=\"img-responsive\" alt=\"...\">\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"col-sm-6 col-md-3 col-lg-3 etc\">\r\n");
      out.write("                <div class=\"portfolio-item\">\r\n");
      out.write("                    <div class=\"hover-bg\">\r\n");
      out.write("                        <a href=\"#\">\r\n");
      out.write("                            <div class=\"hover-text\">\r\n");
      out.write("                                <h4>Sample Image</h4>\r\n");
      out.write("                                <small>Will be changed</small>\r\n");
      out.write("                                <div class=\"clearfix\"></div>\r\n");
      out.write("                                <i class=\"fa fa-plus\"></i>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/img/portfolio/05.jpg\" class=\"img-responsive\" alt=\"...\">\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"col-sm-6 col-md-3 col-lg-3 sysetm\">\r\n");
      out.write("                <div class=\"portfolio-item\">\r\n");
      out.write("                    <div class=\"hover-bg\">\r\n");
      out.write("                        <a href=\"#\">\r\n");
      out.write("                            <div class=\"hover-text\">\r\n");
      out.write("                                <h4>Sample Image</h4>\r\n");
      out.write("                                <small>Will be changed</small>\r\n");
      out.write("                                <div class=\"clearfix\"></div>\r\n");
      out.write("                                <i class=\"fa fa-plus\"></i>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/img/portfolio/06.jpg\" class=\"img-responsive\" alt=\"...\">\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"col-sm-6 col-md-3 col-lg-3 sysetm etc\">\r\n");
      out.write("                <div class=\"portfolio-item\">\r\n");
      out.write("                    <div class=\"hover-bg\">\r\n");
      out.write("                        <a href=\"#\">\r\n");
      out.write("                            <div class=\"hover-text\">\r\n");
      out.write("                                <h4>Sample Image</h4>\r\n");
      out.write("                                <small>Will be changed</small>\r\n");
      out.write("                                <div class=\"clearfix\"></div>\r\n");
      out.write("                                <i class=\"fa fa-plus\"></i>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/img/portfolio/07.jpg\" class=\"img-responsive\" alt=\"...\">\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"col-sm-6 col-md-3 col-lg-3 model\">\r\n");
      out.write("                <div class=\"portfolio-item\">\r\n");
      out.write("                    <div class=\"hover-bg\">\r\n");
      out.write("                        <a href=\"#\">\r\n");
      out.write("                            <div class=\"hover-text\">\r\n");
      out.write("                                <h4>Sample Image</h4>\r\n");
      out.write("                                <small>Will be changed</small>\r\n");
      out.write("                                <div class=\"clearfix\"></div>\r\n");
      out.write("                                <i class=\"fa fa-plus\"></i>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/img/portfolio/08.jpg\" class=\"img-responsive\" alt=\"...\">\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <nav id=\"footer\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\tCopyright (c) LibOutcomes Hansung Univ. Sung Jae Park Alright Reserved\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t<big>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\">박성재</a>\r\n");
      out.write("\t\t\t\t</big><br>\r\n");
      out.write("\t\t\t\t<small>\r\n");
      out.write("\t\t\t\t\t한성대 지식정보학과<br><br>\r\n");
      out.write("\t\t\t\t\t서울 특별시 삼선구 삼선동2가 389 한성대학교 연구관 529호\r\n");
      out.write("\t\t\t\t</small>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- jQuery (부트스트랩의 자바스크립트 플러그인을 위해 필요합니다) -->\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/js/jquery.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/js/bootstrap.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/js/jquery.isotope.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/js/owl.carousel.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/js/main.js\" type=\"text/javascript\"></script> \r\n");
      out.write("    \r\n");
      out.write("    <!-- include summernote js/lang -->\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/js/summernote.min.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/js/summernote-ko-KR.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <!-- 액션 -->\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/js/public/loginFunction.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/js/public/boardFunction.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- Script to Activate the Summernote -->\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$(document).ready(function() {\r\n");
      out.write("\t\t\t$('#summernote').summernote({\r\n");
      out.write("\t\t\t\theight: 300,\r\n");
      out.write("\t\t\t\tlang: 'ko-KR'\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write(" \r\n");
      out.write("</body>\r\n");
      out.write(" \r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /WEB-INF/page/header.jsp(83,20) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginId eq null || loginId == ''}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("                        <a href=\"Login\" class=\"btn navbar-btn btn-primary\">로그인</a>\r\n");
        out.write("                    ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f1.setParent(null);
    // /WEB-INF/page/header.jsp(86,20) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginId ne null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
    if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("                        <a href=\"Logout\" class=\"btn navbar-btn btn-danger\">로그아웃</a>\r\n");
        out.write("                    ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
    return false;
  }
}
